It will result in an undefined exception control. You must add try-catch block to run the code.